title: "Vanshika Sharma's Portfolio"
description: "Data Scientist specializing in NLP and Generative AI"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Vanshika-sh.github.io" # the base hostname & protocol for your site
logo: IMG_4069.jpg

# GitHub settings
github_username: Vanshika-sh

# Theme settings
theme: jekyll-theme-minimal

# Site settings
name: "Vanshika Sharma"
email: vanshika.sh3143@gmail.com
phone: +1 862-433-9846
linkedin_username: vanshika-sharma-30112020
github_username: Vanshika-sh
twitter_username: your_twitter_username # if applicable
google_analytics: UA-XXXXXXXX-X # your Google Analytics tracking ID

# Social links
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/vanshika-sharma-30112020/
  - name: GitHub
    url: https://github.com/Vanshika-sh
  - name: TowardsDataScience
    url: https://towardsdatascience.com/resnets-why-do-they-perform-better-than-classic-convnets-conceptual-analysis-6a9c82e06e53

# Navigation links
nav_links:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
  - name: "Projects"
    url: "/projects"
  - name: "Blog"
    url: "/blog"
  - name: "Contact"
    url: "/contact"

# Colors (only some themes support this, minima doesn't)
# colors:
#   background: "#ffffff"
#   text: "#333333"
#   link: "#1e90ff"
#   sidebar: "#f5f5f5"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Other settings
markdown: kramdown
highlighter: rouge
permalink: pretty


